using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using IMMO.DAL;



        //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immo_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public class AmmortissementLite
    {
        public string ARTICLE { get; set; }
        public decimal ANNEE { get; set; }
        public Nullable<System.DateTime> DATEAMORTISSEMENT { get; set; }
        public Nullable<decimal> VALEUR { get; set; }
        public Nullable<decimal> MONTANTCALCUL { get; set; }
        public Nullable<decimal> AMORTISSEMENTP { get; set; }
        public Nullable<decimal> AMORTISSEMENTNONCPT { get; set; }
    
        public virtual IMMO_ARTICLE IMMO_ARTICLE { get; set; }
    }
}

   