//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODEBAR
    {
        public string CODECLAIR { get; set; }
        public string CODEBAR1 { get; set; }
        public string LIBELLE { get; set; }
        public string AFFECTLOCAL { get; set; }
        public string CODE { get; set; }
    
        public virtual IMMO_ARTICLE IMMO_ARTICLE { get; set; }
    }
}
