//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_INV_LIVRE
    {
        public decimal ANNEE { get; set; }
        public string ARTICLE { get; set; }
        public string AFFECTATIONTH { get; set; }
        public string AFFECTATIONPHY { get; set; }
        public string EXISTE { get; set; }
        public string EMPLACEMENT { get; set; }
        public string OBSERVATION { get; set; }
        public Nullable<System.DateTime> DATEACQUISITION { get; set; }
        public Nullable<decimal> VALEURCOMPTABLE { get; set; }
        public Nullable<System.DateTime> DATEEXPLOITATION { get; set; }
        public Nullable<decimal> TAUXAMORTISSEMENT { get; set; }
        public string JOURNALINVENTAIRE { get; set; }
        public string SERVICE { get; set; }
        public string LOCALE { get; set; }
        public string FAMILLECPT { get; set; }
        public string DESIGNATIONARTICLE { get; set; }
        public string LIBELLEAFFECTATION { get; set; }
        public Nullable<decimal> DOTATIONANTERIEURE { get; set; }
        public Nullable<decimal> DOTATIONEXERCICE { get; set; }
        public Nullable<decimal> DUREE { get; set; }
        public string AMORTI { get; set; }
        public string RESPONSABLEACHAT { get; set; }
        public Nullable<System.DateTime> DATEAMORTISSEMENT { get; set; }
    }
}
