//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_FACTURE
    {
        public IMMO_FACTURE()
        {
            this.IMMO_DETAILFACTURE = new HashSet<IMMO_DETAILFACTURE>();
        }
    
        public string NUM { get; set; }
        public string REFERENCE { get; set; }
        public string FOURNISSEUR { get; set; }
        public string OBSERVATION { get; set; }
        public decimal MONTANTTTC { get; set; }
        public decimal MONTANTHT { get; set; }
        public decimal CHARGERATTACHEIMMO { get; set; }
        public decimal CHARGENONRATTACHEIMMO { get; set; }
        public string ETAT { get; set; }
        public Nullable<decimal> TVARECPERATION { get; set; }
        public System.DateTime DATEFACTURE { get; set; }
    
        public virtual ICollection<IMMO_DETAILFACTURE> IMMO_DETAILFACTURE { get; set; }
        public virtual IMMO_FOURNISSEUR IMMO_FOURNISSEUR { get; set; }
    }
}
