//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_INVETAIRE_ARTICLE
    {
        public decimal ANNEE { get; set; }
        public decimal NUM { get; set; }
        public string ARTICLE { get; set; }
        public string AFFECTATION { get; set; }
        public string EXISTE { get; set; }
        public string OPERATEUR { get; set; }
        public string EMPLACEMENT { get; set; }
        public string OBSERVATION { get; set; }
        public string AFFECTATIONTH { get; set; }
    
        public virtual IMMO_AFFECTATION IMMO_AFFECTATION { get; set; }
        public virtual IMMO_ARTICLE IMMO_ARTICLE { get; set; }
        public virtual IMMO_INVENTAIRE IMMO_INVENTAIRE { get; set; }
    }
}
