//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_EMPLACEMENT
    {
        public IMMO_EMPLACEMENT()
        {
            this.IMMO_ARTICLE = new HashSet<IMMO_ARTICLE>();
        }
    
        public string CODE { get; set; }
        public string LIEU { get; set; }
        public string ETAGE { get; set; }
        public string COULOIR { get; set; }
        public string BUREAU { get; set; }
        public string LOCAL { get; set; }
    
        public virtual IMMO_LOCAL IMMO_LOCAL { get; set; }
        public virtual ICollection<IMMO_ARTICLE> IMMO_ARTICLE { get; set; }
    }
}
