//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_TVA
    {
        public decimal CODE { get; set; }
        public decimal VALEUR { get; set; }
    }
}
