//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_CESSION
    {
        public IMMO_CESSION()
        {
            this.IMMO_ARTICLE_SESSION = new HashSet<IMMO_ARTICLE_SESSION>();
        }
    
        public decimal ANNEE { get; set; }
        public decimal NUM { get; set; }
        public System.DateTime DATECESSION { get; set; }
        public string RAISON { get; set; }
        public string ETAT { get; set; }
        public Nullable<decimal> VALTOTAL { get; set; }
        public decimal EXERCICE { get; set; }
    
        public virtual ICollection<IMMO_ARTICLE_SESSION> IMMO_ARTICLE_SESSION { get; set; }
    }
}
