//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_FAMILLE
    {
        public IMMO_FAMILLE()
        {
            this.IMMO_ARTICLE = new HashSet<IMMO_ARTICLE>();
            this.IMMO_DETAILBL = new HashSet<IMMO_DETAILBL>();
            this.IMMO_ARTICLESUPPRIME = new HashSet<IMMO_ARTICLESUPPRIME>();
        }
    
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public string COMPTE { get; set; }
        public string FAMILLEM { get; set; }
    
        public virtual ICollection<IMMO_ARTICLE> IMMO_ARTICLE { get; set; }
        public virtual IMMO_COMPTE IMMO_COMPTE { get; set; }
        public virtual ICollection<IMMO_DETAILBL> IMMO_DETAILBL { get; set; }
        public virtual IMMO_FAMILLEM IMMO_FAMILLEM { get; set; }
        public virtual ICollection<IMMO_ARTICLESUPPRIME> IMMO_ARTICLESUPPRIME { get; set; }
    }
}
