//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_ARTICLE_SESSION
    {
        public string ARTICLE { get; set; }
        public string RAISON { get; set; }
        public decimal VALEUR { get; set; }
        public System.DateTime DATESESSION { get; set; }
        public string ETAT { get; set; }
        public Nullable<decimal> DOTATION { get; set; }
        public decimal ANNEE { get; set; }
        public decimal NUM { get; set; }
        public Nullable<decimal> AMORTISSEMENTPRATIQUE { get; set; }
    
        public virtual IMMO_ARTICLE IMMO_ARTICLE { get; set; }
        public virtual IMMO_CESSION IMMO_CESSION { get; set; }
    }
}
