//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_LOCAL
    {
        public IMMO_LOCAL()
        {
            this.IMMO_ARTICLE = new HashSet<IMMO_ARTICLE>();
            this.IMMO_EMPLACEMENT = new HashSet<IMMO_EMPLACEMENT>();
        }
    
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
    
        public virtual ICollection<IMMO_ARTICLE> IMMO_ARTICLE { get; set; }
        public virtual ICollection<IMMO_EMPLACEMENT> IMMO_EMPLACEMENT { get; set; }
    }
}
