//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_DETAILBL
    {
        public IMMO_DETAILBL()
        {
            this.IMMO_ARTICLE = new HashSet<IMMO_ARTICLE>();
            this.IMMO_DETAILFACTURE = new HashSet<IMMO_DETAILFACTURE>();
        }
    
        public decimal ANNEEBL { get; set; }
        public decimal NUMBL { get; set; }
        public decimal NUM { get; set; }
        public string FAMILLE { get; set; }
        public decimal QTE { get; set; }
        public decimal QTEFACTURE { get; set; }
        public decimal PRIXUNITAIRE { get; set; }
        public string OBSERVATION { get; set; }
        public string AFFECTATION { get; set; }
        public string SERVICE { get; set; }
        public string LOCALE { get; set; }
    
        public virtual ICollection<IMMO_ARTICLE> IMMO_ARTICLE { get; set; }
        public virtual IMMO_BL IMMO_BL { get; set; }
        public virtual ICollection<IMMO_DETAILFACTURE> IMMO_DETAILFACTURE { get; set; }
        public virtual IMMO_FAMILLE IMMO_FAMILLE { get; set; }
    }
}
