//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_DETAILFACTURE
    {
        public IMMO_DETAILFACTURE()
        {
            this.IMMO_ARTICLE = new HashSet<IMMO_ARTICLE>();
        }
    
        public string NUMFACTURE { get; set; }
        public decimal ANNEEBL { get; set; }
        public decimal NUMBL { get; set; }
        public decimal NUMLIGNEBL { get; set; }
        public decimal MONTANTHT { get; set; }
        public Nullable<decimal> TVA { get; set; }
        public decimal MONTANTTTC { get; set; }
        public decimal QTE { get; set; }
        public decimal VALEURCOMPTABLE { get; set; }
        public Nullable<decimal> PRIXUNITAIREHT { get; set; }
    
        public virtual ICollection<IMMO_ARTICLE> IMMO_ARTICLE { get; set; }
        public virtual IMMO_DETAILBL IMMO_DETAILBL { get; set; }
        public virtual IMMO_FACTURE IMMO_FACTURE { get; set; }
    }
}
