//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_BL
    {
        public IMMO_BL()
        {
            this.IMMO_DETAILBL = new HashSet<IMMO_DETAILBL>();
        }
    
        public decimal ANNEE { get; set; }
        public decimal NUM { get; set; }
        public string REFCOMMANDE { get; set; }
        public System.DateTime DATECOMMANDE { get; set; }
        public string CENTREACHAT { get; set; }
        public string FOURNISSEUR { get; set; }
        public System.DateTime DATELIVRAISON { get; set; }
        public string OBSERVATION { get; set; }
        public string ETAT { get; set; }
        public string REFERENCE { get; set; }
        public decimal EXERCICE { get; set; }
    
        public virtual IMMO_AFFECTATION IMMO_AFFECTATION { get; set; }
        public virtual IMMO_FOURNISSEUR IMMO_FOURNISSEUR { get; set; }
        public virtual ICollection<IMMO_DETAILBL> IMMO_DETAILBL { get; set; }
    }
}
