//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_FOURNISSEUR
    {
        public IMMO_FOURNISSEUR()
        {
            this.IMMO_BL = new HashSet<IMMO_BL>();
            this.IMMO_FACTURE = new HashSet<IMMO_FACTURE>();
        }
    
        public string CODE { get; set; }
        public string NOM { get; set; }
        public string RESPONSABLE { get; set; }
        public string MATFISCAL { get; set; }
        public string ADRESSE { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string CONTACT { get; set; }
    
        public virtual ICollection<IMMO_BL> IMMO_BL { get; set; }
        public virtual ICollection<IMMO_FACTURE> IMMO_FACTURE { get; set; }
    }
}
