//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_INV_COMPTABILITE
    {
        public decimal ANNEE { get; set; }
        public System.DateTime DATEAMORTISSEMENT { get; set; }
        public string FAMILLECPT { get; set; }
        public string CONTREPARTIE { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public string LIBELLE { get; set; }
    }
}
