//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMO_INVENTAIRE
    {
        public IMMO_INVENTAIRE()
        {
            this.IMMO_INVETAIRE_ARTICLE = new HashSet<IMMO_INVETAIRE_ARTICLE>();
        }
    
        public decimal ANNEE { get; set; }
        public decimal NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public string ETAT { get; set; }
        public Nullable<System.DateTime> DATEVALIDATION { get; set; }
        public Nullable<System.DateTime> DATECLOTURE { get; set; }
        public string AUTOMATIQUE { get; set; }
        public string MUTATION { get; set; }
    
        public virtual ICollection<IMMO_INVETAIRE_ARTICLE> IMMO_INVETAIRE_ARTICLE { get; set; }
    }
}
