//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ARTMMB
    {
        public string CODE { get; set; }
        public string COD_INV { get; set; }
        public string LIBELLE { get; set; }
        public string AFFECT { get; set; }
        public string SERVICE { get; set; }
        public string LOCALE { get; set; }
        public Nullable<System.DateTime> D_ACHAT { get; set; }
        public Nullable<decimal> P_ACHAT { get; set; }
        public Nullable<System.DateTime> D_AMORT { get; set; }
        public string M_AMORT { get; set; }
        public Nullable<decimal> T_AMORT { get; set; }
        public string CODABAR { get; set; }
        public Nullable<System.DateTime> DAT_MUT { get; set; }
        public Nullable<System.DateTime> DAT_INV { get; set; }
        public Nullable<System.DateTime> DAT_FIN { get; set; }
    }
}
