//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FAMMMB
    {
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<decimal> NBART { get; set; }
        public Nullable<decimal> T_AMORT { get; set; }
    }
}
